import type { AnalysisResult } from "./schemas.js";

export function renderMarkdown(result: AnalysisResult, includeEvidence = true): string {
  const { profile } = result;
  const lines: string[] = [
    `# Technical Dossier — @${profile.username}`,
    "",
    `_Generated by git-mentor · ${profile.analyzedAt}_`,
    "",
    "## Summary",
    profile.summary,
    "",
    `**Maturity score:** ${profile.maturityScore}/10`,
    `**Public repos analyzed:** ${profile.repoCount}`,
    `**Total stars:** ${profile.totalStars}`,
    "",
    "## Primary Stack",
    profile.primaryStack.join(", ") || "_None detected_",
    "",
    "## Skills",
  ];

  for (const skill of profile.skills) {
    lines.push(`- **${skill.name}** — ${skill.level} (${skill.score}/10, ${skill.confidence})`);
    if (includeEvidence) {
      for (const ev of skill.evidence.slice(0, 2)) {
        const url = ev.url ? ` — ${ev.url}` : "";
        lines.push(`  - _${ev.type}_: ${ev.title}${url}`);
      }
    }
  }

  lines.push("", "## Domains");
  for (const domain of profile.domains) {
    lines.push(`- **${domain.name}** — ${domain.level} (${domain.confidence})`);
  }

  lines.push("", "## Strengths", ...profile.strengths.map((s) => `- ${s}`));
  lines.push("", "## Weaknesses", ...profile.weaknesses.map((w) => `- ${w}`));

  if (result.gapAnalysis) {
    const gap = result.gapAnalysis;
    lines.push(
      "",
      `## Career Gap Analysis — ${gap.targetRole}`,
      "",
      gap.summary,
      "",
      `**Fit score:** ${gap.fitScore}/10`,
      "",
      "### Gaps",
    );
    for (const item of gap.gaps) {
      lines.push(
        `- **${item.area}** (${item.currentLevel} → ${item.targetLevel}) — ${item.rationale}`,
      );
    }
    lines.push("", "### Learning Plan");
    for (const step of gap.learningPlan) {
      lines.push(`- **${step.title}** [${step.effort}] — ${step.description}`);
    }
  }

  if (result.actionPlan) {
    const plan = result.actionPlan;
    lines.push("", "## Growth Recommendations");
    for (const rec of plan.recommendations) {
      lines.push(`- **${rec.title}** [${rec.effort}] — ${rec.description}`);
    }
    lines.push("", "### Technologies to Learn", ...plan.technologiesToLearn.map((t) => `- ${t}`));
    const repos = plan.github.repos;
    if (repos.length) {
      lines.push("", "### Trending Repos (domain match)");
      for (const repo of repos) {
        lines.push(`- **${repo.fullName}** (${repo.stars}★) — ${repo.relevanceReason}`);
        lines.push(`  ${repo.url}`);
      }
      lines.push("", "### Repositories to Watch", ...repos.map((r) => `- \`${r.fullName}\``));
    }
    if (plan.github.profiles.length) {
      lines.push("", "### Profiles to Follow");
      for (const entry of plan.github.profiles) {
        lines.push(`- **@${entry.username}** — ${entry.relevanceReason}`);
        lines.push(`  ${entry.url}`);
      }
    }
    if (plan.profileImprovements.length) {
      lines.push("", "### Profile Improvements");
      for (const item of plan.profileImprovements) {
        lines.push(`- **[${item.category}] ${item.title}** — ${item.action}`);
      }
    }
  }

  if (result.traces.length) {
    lines.push("", "## Agent Trace");
    for (const trace of result.traces) {
      lines.push(
        `- \`${trace.agent}\` / ${trace.step} — ${trace.durationMs}ms — ${trace.outputSummary}`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}
