"""Export analysis results to Markdown."""

from __future__ import annotations

from git_mentor.core.schemas import AnalysisResult


def render_markdown(result: AnalysisResult, *, include_evidence: bool = True) -> str:
    profile = result.profile
    lines = [
        f"# Technical Dossier — @{profile.username}",
        "",
        f"_Generated by git-mentor · {profile.analyzed_at.isoformat()}_",
        "",
        "## Summary",
        profile.summary,
        "",
        f"**Maturity score:** {profile.maturity_score}/10",
        f"**Public repos analyzed:** {profile.repo_count}",
        f"**Total stars:** {profile.total_stars}",
        "",
        "## Primary Stack",
        ", ".join(profile.primary_stack) or "_None detected_",
        "",
        "## Skills",
    ]

    for skill in profile.skills:
        lines.append(
            f"- **{skill.name}** — {skill.level.value} ({skill.score}/10, {skill.confidence.value})"
        )
        if include_evidence:
            for ev in skill.evidence[:2]:
                url = f" — {ev.url}" if ev.url else ""
                lines.append(f"  - _{ev.type.value}_: {ev.title}{url}")

    lines.extend(["", "## Domains"])
    for domain in profile.domains:
        lines.append(f"- **{domain.name}** — {domain.level.value} ({domain.confidence.value})")

    lines.extend(["", "## Strengths"])
    lines.extend(f"- {s}" for s in profile.strengths)

    lines.extend(["", "## Weaknesses"])
    lines.extend(f"- {w}" for w in profile.weaknesses)

    if result.gap_analysis:
        gap = result.gap_analysis
        lines.extend(
            [
                "",
                f"## Career Gap Analysis — {gap.target_role}",
                "",
                gap.summary,
                "",
                f"**Fit score:** {gap.fit_score}/10",
                "",
                "### Gaps",
            ]
        )
        for item in gap.gaps:
            lines.append(
                f"- **{item.area}** ({item.current_level.value} → {item.target_level.value}) — {item.rationale}"
            )

        lines.extend(["", "### Learning Plan"])
        for step in gap.learning_plan:
            lines.append(f"- **{step.title}** [{step.effort}] — {step.description}")

    if result.action_plan:
        plan = result.action_plan
        lines.extend(["", "## Growth Recommendations"])
        for rec in plan.recommendations:
            lines.append(f"- **{rec.title}** [{rec.effort}] — {rec.description}")
        lines.extend(["", "### Technologies to Learn"])
        lines.extend(f"- {t}" for t in plan.technologies_to_learn)
        lines.extend(["", "### Repositories to Watch"])
        lines.extend(f"- `{r}`" for r in plan.repos_to_watch)

    if result.traces:
        lines.extend(["", "## Agent Trace"])
        for trace in result.traces:
            lines.append(
                f"- `{trace.agent}` / {trace.step} — {trace.duration_ms}ms — {trace.output_summary}"
            )

    return "\n".join(lines) + "\n"
